apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    run: demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: demoapp
  template:
    metadata:
      labels:
        run: demoapp
    spec:
      containers:
      - name: dockerdemo
        image: dockerdemo
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-svc
spec:
  type: NodePort
  selector:
    run: demoapp
  ports:
    - protocol: TCP
      port: 8080  